name:  active_query
description: >
  active_query allows you to easily watch the DOM for elements that match and
  un-match CSS selectors.
version: 0.1.0-dev
author: Justin Fagnani <justinfagnani@google.com>
homepage: https://github.com/justinfagnani/active_query.dart
dev_dependencies:
  browser: any
  unittest: '>= 0.10.0 < 0.12.0'
